# Home Assistant Configuration
# Add this to your configuration.yaml file

# REST commands for YouTube thumbs rating
rest_command:
  youtube_thumbs_up:
    url: "http://10.0.0.142:21812/thumbs_up"
    method: POST
    timeout: 30
    
  youtube_thumbs_down:
    url: "http://10.0.0.142:21812/thumbs_down"
    method: POST
    timeout: 30

# Optional: Create a sensor to check current song rating status
sensor:
  - platform: rest
    name: "YouTube Song Status"
    resource: "http://10.0.0.142:21812/status"
    method: GET
    timeout: 10
    scan_interval: 30
    json_attributes:
      - song
      - artist
      - rating
      - video_id
    value_template: "{{ value_json.rating | default('unknown') }}"

# Example automation: Map Lutron remote buttons to thumbs up/down
# Adjust the trigger based on your specific Lutron remote setup
automation:
  - alias: "Lutron Remote - Thumbs Up"
    trigger:
      - platform: event
        event_type: lutron_event  # Adjust based on your Lutron integration
        event_data:
          button: "button_1"  # Adjust to your button ID
    action:
      - service: rest_command.youtube_thumbs_up
  
  - alias: "Lutron Remote - Thumbs Down"
    trigger:
      - platform: event
        event_type: lutron_event  # Adjust based on your Lutron integration
        event_data:
          button: "button_2"  # Adjust to your button ID
    action:
      - service: rest_command.youtube_thumbs_down

# Optional: Scripts for easier calling
script:
  rate_song_thumbs_up:
    alias: "Rate Song Thumbs Up"
    sequence:
      - service: rest_command.youtube_thumbs_up
      
  rate_song_thumbs_down:
    alias: "Rate Song Thumbs Down"
    sequence:
      - service: rest_command.youtube_thumbs_down
